In [1]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 56.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 33.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 72.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 68.9 MB/s eta 0:00:00


In [3]:
!pip install xformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.1/109.1 MB 9.8 MB/s eta 0:00:00


In [4]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [13]:
classifier('I am Batman')

[{'label': 'POSITIVE', 'score': 0.9981045722961426}]

In [17]:
classifier = pipeline('sentiment-analysis', model='nlptown/bert-base-multilingual-uncased-sentiment')

In [18]:
classifier('this is not that bad')

[{'label': '3 stars', 'score': 0.46889108419418335}]

In [19]:
classifier('Esperamos que no lo odie.')

[{'label': '3 stars', 'score': 0.3368820548057556}]

In [22]:
classifier('అస్సలు మంచిది')

[{'label': '4 stars', 'score': 0.3283419609069824}]

In [23]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [24]:
model_name = 'nlptown/bert-base-multilingual-uncased-sentiment'
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline('sentiment-analysis', tokenizer=tokenizer, model=model)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [31]:
classifier('I am')

[{'label': '5 stars', 'score': 0.458522766828537}]

In [37]:
input = tokenizer('some sentence is being fed here',
                  padding=True,
                  truncation=True,
                  max_length=256,
                  return_tensors='tf')
input

{'input_ids': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=
array([[  101, 10970, 45261, 10127, 11352, 42639, 14048,   102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [36]:
input = tokenizer('I am god')
input

{'input_ids': [101, 151, 10345, 13131, 102], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}

In [41]:
output = model(input)

In [45]:
output[0]

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-0.05970388,  0.7570636 ,  1.140129  , -0.0642983 , -1.4674855 ]],
      dtype=float32)>